### ISSUE TITLE
[request] update to use with twig 2.0

### ISSUE THREAD

**Issue by B0bbyD0llar** [GeckoPackages/GeckoTwig#19]
Hi,
can this package updated to use with twig 2.0?

**Comment by SpacePossum** [comment]
Hi,
This package can be used with Twig 2.0, do you encounter any problems with it on Twig 2.0?

**Comment by B0bbyD0llar** [comment]
i can't install.
`composer.phar require gecko-packages/gecko-twig`
gets
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gecko-packages/gecko-twig ^1.3 -> satisfiable by gecko-packages/gecko-twig[v1.3].
    - gecko-packages/gecko-twig v1.3 requires twig/twig ^1.26.0 -> satisfiable by twig/twig[1.x-dev, v1.26.0, v1.26.1, v1.27.0, v1.28.0, v1.28.1, v1.28.2, v1.29.0, v1.30.0, v1.31.0] but these conflict with your requirements or minimum-stability.`

**Comment by SpacePossum** [comment]
Ah I see, I prepared for 2.x but before it was released but never pushed a new version of the package.
I'll work on this :)
Thanks!

**Comment by SpacePossum** [comment]
@B0bbyD0llar please see https://github.com/GeckoPackages/GeckoTwig/pull/20
that is how the upcoming release for Twig 2.x will look like. Let me know if have to review/test, otherwise I just move on with merging and releasing soon :)

**Comment by SpacePossum** [comment]
v2.0 has been released of this package, supporting Twig 2.0
https://github.com/GeckoPackages/GeckoTwig/releases/tag/v2.0 &
https://packagist.org/packages/gecko-packages/gecko-twig

thanks for reporting :)

**Comment by B0bbyD0llar** [comment]
works great. Thanks a lot.
